title: "Festa Trail"
url: "https://festatrail.com"
baseurl: ""
locale: "fr_FR"
permalink: "pretty"
robots: "index,follow"
logo: "/assets/img/logo.png"
image: "/assets/img/og-default.jpg"

plugins:
  - jekyll-sitemap
